# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

title: Jernej Strasner
description: A blog.
#disqus_shortname: shortname

#url: http://jernejstrasner.github.io/
url: http://localhost:4000/

owner:
    name: Jernej Strasner
    avatar: avatar.jpg
    bio: "My bio"
    email: jernej.strasner@gmail.com
    twitter: JernejStrasner
    github: jernejstrasner

timezone: Europe/Ljubljana
future: true
highlighter: true
markdown: kramdown

reading_time: true
words_per_minute: 200

paginate: 5

