baseURL = "http://jernejstrasner.com/"
languageCode = "en-us"
title = "Jernej Strasner"
theme = "hello-friend-ng"
paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
#   homeSubtitle = "A personal website"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Jernej Strasner's personal website"
  keywords = "homepage, blog, jernej, strasner, specto"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    # subtitle = "A personal website"
    copyright = 'Jernej Strasner'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "jernej"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/jernejstrasner/"
  [[menu.main]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com/JernejStrasner/"